In [47]:
## RAGAS is a framework for evaluating the RAG pipeline.

## Metrics:
# 1. Context Relevancy: Measures how relevant the retrieved context is to the question asked.
#    It filters out irrelevant information from the retrieved context.
#    Calculated as: number of relevant sentences in context / total sentences in context.

# 2. Context Precision: Measures the signal-to-noise ratio of the retrieved context.
#    It evaluates whether the relevant chunks are ranked higher than irrelevant ones.
#    Calculated as: mean of precision@k for each relevant chunk in the ranked retrieved context,
#    where precision@k = number of relevant chunks in top-k / k.

# 3. Context Recall: Measures how much of the ground truth is captured in the retrieved context.
#    It checks if all the necessary information to answer the question was retrieved.
#    Calculated as: Recall@K = number of ground truth sentences attributable to context / total sentences in ground truth.

# 4. Faithfulness: Measures how factually consistent the generated answer is with the retrieved context.
#    It ensures the answer does not contain information not present in the context (no hallucinations).
#    Calculated as: number of answer statements that can be inferred from context / total statements in answer.

# 5. Answer Relevancy: Measures how relevant the generated answer is to the original question.
#    It penalizes answers that are incomplete or contain redundant information.
#    Calculated as: mean cosine similarity between the original question and n questions
#    generated from the answer, using embeddings to capture semantic similarity.

In [48]:
import nest_asyncio
nest_asyncio.apply()  # Allow asyncio to run inside Jupyter's existing event loop (needed by RAGAS)

import ragas
print(ragas.__version__)

import os
import pandas as pd
from dotenv import load_dotenv

# LangChain components
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import DirectoryLoader
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_chroma import Chroma
from langchain_openai import ChatOpenAI

# RAGAS wrappers to make LangChain LLM/Embeddings compatible with RAGAS
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

# Euriai embeddings (used for vector similarity)
from euriai.langchain import EuriaiEmbeddings

# Load environment variables from app/.env file
app_dir = os.path.join(os.getcwd(), "app")
load_dotenv(os.path.join(app_dir, ".env"))

0.4.3

True

In [55]:
api_key = os.getenv("key")

# ── Option 1 (Active): OpenRouter free model via ChatOpenAI ───────────────────
# Good for testing — no cost, but may have rate limits and weaker reasoning.
# llm = ChatOpenAI(
#     model="stepfun/step-3.5-flash:free",
#     base_url="https://openrouter.ai/api/v1",
#     api_key="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",
# )

# ── Option 2 (Alternative): Euriai GPT-4o-mini ────────────────────────────────
# Better quality but requires Euriai API key. Uncomment below to use instead.
from euriai.langchain import create_chat_model
llm = create_chat_model(api_key=api_key, model="gpt-4o-mini", temperature=0.7)

# Single alias so all downstream cells reference the same model
model = llm

# Quick sanity-check — verify the LLM responds correctly before running RAGAS
response = llm.invoke("What is the capital of France?")
print("LLM test response:", response.content)

# ── Embeddings: Euriai text-embedding-3-small ─────────────────────────────────
# Used for both vector store (Chroma) and RAGAS answer relevancy metric
embeddings = EuriaiEmbeddings(
    api_key=api_key,
    model="text-embedding-3-small"
)

LLM test response: The capital of France is Paris.

In [56]:
# Load all .txt files from the data/ directory as LangChain Documents
loader = DirectoryLoader("./data", glob="**/*.txt")
docs = loader.load()

# Split documents into smaller chunks for the vector store
# chunk_size=350 tokens, chunk_overlap=20 for context continuity
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=350,
    chunk_overlap=20,
    length_function=len,
    is_separator_regex=False,
)
chunks = text_splitter.split_documents(docs)

print(f"Loaded {len(docs)} documents → split into {len(chunks)} chunks")

Loaded 3 documents → split into 33 chunks

In [57]:
docs

[Document(metadata={'source': 'data\\food.txt'}, page_content='margherita pizza; $12; classic with tomato, mozzarella, and basil; main dish\n\nspaghetti carbonara; $15; creamy pasta with pancetta and parmesan; main dish\n\nbruschetta; $8; toasted bread with tomato, garlic, and olive oil; appetizer\n\ncaprese salad; $10; fresh tomatoes, mozzarella, and basil; salad\n\nlasagna; $14; layered pasta with meat sauce and cheese; main dish\n\ntiramisu; $9; coffee-flavored italian dessert; dessert\n\ngelato; $7; traditional italian ice cream; dessert\n\nrisotto milanese; $16; creamy saffron-infused rice dish; main dish\n\npolenta; $11; cornmeal dish, often served as a side; side dish\n\nosso buco; $20; braised veal shanks with vegetables and broth; main dish\n\nravioli; $13; stuffed pasta with cheese or meat filling; main dish\n\nminestrone soup; $9; vegetable soup with pasta or rice; soup\n\nprosecco; $8; italian sparkling white wine; drink\n\nchianti; $10; dry red wine from tuscany; drink\n\nfocaccia; $6; oven-baked italian bread; side dish\n\ncalamari; $12; fried squid rings with marinara sauce; appetizer\n\nespresso; $4; strong italian coffee; drink\n\ncannoli; $8; sicilian pastry with sweet ricotta filling; dessert\n\narancini; $10; fried rice balls stuffed with cheese or meat; appetizer\n\npanna cotta; $9; creamy italian dessert with caramel or fruit; dessert\n\nnegroni; $12; cocktail with gin, vermouth, and campari; drink\n\naperol spritz; $10; aperitif cocktail with aperol, prosecco, and soda; drink\n\ngnocchi; $14; potato-based pasta served with various sauces; main dish\n\npanzanella; $9; bread and tomato salad; salad\n\ncarpaccio; $15; thinly sliced raw beef with arugula and parmesan; appetizer\n\naffogato; $7; espresso poured over gelato; dessert\n\nbiscotti; $5; crunchy italian almond biscuits; dessert\n\nvitello tonnato; $18; thin slices of veal with a creamy tuna sauce; main dish\n\ncrostini; $7; small toasted bread with toppings; appetizer\n\nzabaglione; $10; light custard dessert made with egg yolks; dessert\n\nfrittata; $12; italian-style omelette; main dish\n\nsaltimbocca; $19; veal wrapped in prosciutto and sage; main dish\n\nlimoncello; $8; italian lemon liqueur; drink\n\ngrappa; $9; italian grape-based brandy; drink\n\nsangiovese; $11; medium-bodied red wine; drink\n\nribollita; $10; tuscan bread and vegetable soup; soup\n\ntortellini; $14; ring-shaped pasta filled with meat or cheese; main dish\n\npanettone; $15; traditional italian christmas bread; dessert\n\ninsalata mista; $8; mixed green salad with italian dressing; salad\n\ncacio e pepe; $13; pasta with cheese and pepper; main dish\n\nitalian soda; $5; carbonated water with flavored syrup; drink\n\namericano; $6; coffee with added hot water; drink\n\nfrutti di mare; $22; seafood pasta with mixed shellfish; main dish\n\ncaponata; $9; eggplant dish with capers, olives, and celery; side dish\n\namaretto sour; $10; cocktail with amaretto, lemon juice, and sugar; drink\n\nbranzino; $21; mediterranean sea bass, usually grilled or baked; main dish\n\nporchetta; $18; savory, fatty, and moist boneless pork roast; main dish\n\nmontepulciano wine; $12; full-bodied red wine; drink\n\nbresaola; $14; air-dried, salted beef served as an appetizer; appetizer\n\npesto pasta; $12; pasta with traditional basil pesto sauce; main dish'),
 Document(metadata={'source': 'data\\founder.txt'}, page_content='In the heart of the old quarter of Palermo, amidst the bustling market stalls and the echoes of lively street life, Amico was born into a family where food was more than sustenance—it was the language of love. Raised in the warmth of his Nonna Lucia\'s kitchen, young Amico was captivated by the symphony of flavors and aromas that danced in the air, a testament to his family’s Sicilian heritage.\n\nAmico\'s life was deeply entwined with the vibrant essence of Sicilian cuisine. In the rustic kitchen where his Nonna conjured culinary magic, Amico found his calling. These formative years, filled with the rhythmic chopping of fresh herbs and the sizzling of rich tomato sauces, laid the foundation of his passion for cooking.\n\nThe Journey to Chef Amico\n\nFrom a young age, Amico was immersed in the art of Sicilian cooking. His days were punctuated by visits to the bustling markets of Palermo, where he learned to choose the freshest fish from the Mediterranean and the ripest fruits kissed by the Sicilian sun. These experiences not only sharpened his culinary skills but also deepened his respect for the land and its bounty.\n\nAs he grew, so did his desire to explore beyond the shores of Sicily. Venturing through Italy, Amico worked alongside renowned chefs, each teaching him a new facet of Italian cuisine. From the rolling hills of Tuscany to the romantic canals of Venice, he absorbed the diverse regional flavors, techniques, and traditions that would later influence his unique culinary style.\n\nCreating Chef Amico’s Restaurant\n\nReturning to Palermo with a vision, Amico opened the doors to "Chef Amico," a restaurant that was a culmination of his travels and a tribute to his Sicilian roots. Nestled in a quaint corner of the city, the restaurant quickly gained fame for its authentic flavors and Amico’s innovative twists on traditional recipes.\n\nAt Chef Amico, every dish told a story. The menu, a tapestry of Sicilian classics and modern Italian cuisine, reflected Amico’s journey and his commitment to excellence. Patrons were not just diners; they were part of an extended family, welcomed with the same warmth and joy that Amico had experienced in his Nonna’s kitchen.\n\nPhilosophy of Hospitality\n\nFor Amico, hospitality was an art form. He believed that a meal was a celebration, a moment to pause and relish life’s simple pleasures. His restaurant was a haven where strangers became friends over plates of arancini and glasses of Nero d’Avola. The atmosphere he fostered was one of comfort and camaraderie, a place where every guest left with a full stomach and a happy heart.\n\nContinuing the Legacy\n\nToday, Chef Amico stands as a landmark in Palermo, a testament to Amico’s dedication and love for his craft. His spirit of generosity and passion for food extends beyond the restaurant’s walls. He mentors young chefs, shares his knowledge at culinary workshops, and supports local farmers and producers.\n\nAmico’s legacy is not just in the dishes he creates but in the community he nurtures. His story is a tribute to the power of food to connect us, to share our stories, and to celebrate the richness of life. Chef Amico is more than a restaurant; it\'s a home, built on a lifetime of love, learning, and the flavors of Sicily.'),
 Document(metadata={'source': 'data\\restaurant.txt'}, page_content="In the charming streets of Palermo, tucked away in a quaint alley, stood Chef Amico, a restaurant that was more than a mere eatery—it was a slice of Sicilian heaven. Founded by Amico, a chef whose name was synonymous with passion and creativity, the restaurant was a mosaic of his life’s journey through the flavors of Italy.\n\nChef Amico’s doors opened to a world where the aromas of garlic and olive oil were as welcoming as a warm embrace. The walls, adorned with photos of Amico’s travels and family recipes, spoke of a rich culinary heritage. The chatter and laughter of patrons filled the air, creating a symphony as delightful as the dishes served.\n\nOne evening, as the sun cast a golden glow over the city, a renowned food critic, Elena Rossi, stepped into Chef Amico. Her mission was to uncover the secret behind the restaurant's growing fame. She was greeted by Amico himself, whose eyes sparkled with the joy of a man who loved his work.\n\nElena was led to a table adorned with a simple, elegant setting. The first course was Caponata, a melody of eggplant, capers, and sweet tomatoes, which danced on her palate. Next came the Risotto al Nero di Seppia, a dish that told the tale of Sicily’s love affair with the sea. Each spoonful was a revelation, the rich flavors of squid ink harmonizing with the creamy rice.\n\nThe final masterpiece was Cannoli, the crown jewel of Sicilian desserts. As Elena savored the sweet ricotta filling, encased in a perfectly crisp shell, she realized that Chef Amico wasn’t just about the food. It was about the stories, the traditions, and the heart poured into every dish.\n\nLeaving the restaurant, Elena knew her review would sing praises not just of the food, but of the soul of Chef Amico—a place where every dish was a journey through Sicily, and every bite, a taste of Amico’s dream come true.")]

In [58]:
import threading
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset.synthesizers import default_query_distribution

# RAGAS 0.4 requires a 'file_name' key in each document's metadata
# (used internally to track which document each chunk came from)
for document in docs:
    document.metadata["file_name"] = document.metadata["source"]

# Wrap the LangChain LLM and Embeddings in RAGAS-compatible wrappers
generator_llm = LangchainLLMWrapper(llm)
generator_embeddings = LangchainEmbeddingsWrapper(embeddings)

# Initialise the testset generator
generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
)

# default_query_distribution returns a weighted mix of synthesizers:
#   - SingleHopSpecificQuerySynthesizer  (simple factual questions)
#   - MultiHopAbstractQuerySynthesizer   (multi-doc reasoning)
#   - MultiHopSpecificQuerySynthesizer   (specific multi-doc questions)
query_distribution = default_query_distribution(generator_llm)

# ── Why run in a separate thread? ─────────────────────────────────────────────
# Jupyter's kernel already has a running asyncio event loop.
# RAGAS internally calls asyncio.run(), which conflicts with the existing loop.
# nest_asyncio patches this, but on Python 3.12+ it breaks sniffio's async-library
# detection → AsyncLibraryNotFoundError.
# Running RAGAS in a fresh thread gives it a clean event loop with no conflicts.
_result = {}

def _run_generation():
    try:
        _result["testset"] = generator.generate_with_langchain_docs(
            documents=docs,
            testset_size=10,
            query_distribution=query_distribution,
            raise_exceptions=False,  # Skip individual failed samples instead of crashing
        )
    except Exception as e:
        _result["error"] = e

thread = threading.Thread(target=_run_generation)
thread.start()
thread.join()  # Block until generation is complete

# Re-raise any exception that occurred inside the thread
if "error" in _result:
    raise _result["error"]

testset = _result["testset"]

# Preview the generated testset
testset.to_pandas()

C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\195214991.py:13: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(llm)
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\195214991.py:14: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(embeddings)
Applying HeadlinesExtractor: 100%|██████████| 2/2 [00:05<00:00,  2.99s/it]
Applying HeadlineSplitter:   0%|          | 0/3 [00:00<?, ?it/s]Task failed with ValueError: 'headlines' property not found in this node
Applying HeadlineSplitter: 100%|██████████| 3/3 [00:00<00:00, 808.46it/s]

ValueError: 'headlines' property not found in this node

In [59]:
# ── ADVANCED TESTSET GENERATION (optional, more control over transforms) ──────
# Use this cell instead of the simple generation above if you want to:
#   - Customise which document transforms are applied
#   - Skip transforms that crash (e.g. HeadlinesExtractor fails on short docs)
#   - Control exactly what relationships are built in the Knowledge Graph

import threading
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset import TestsetGenerator
from ragas.testset.synthesizers import default_query_distribution
from ragas.testset.graph import NodeType
from ragas.testset.transforms.extractors import EmbeddingExtractor, SummaryExtractor
from ragas.testset.transforms.extractors.llm_based import NERExtractor, ThemesExtractor
from ragas.testset.transforms.filters import CustomNodeFilter
from ragas.testset.transforms.relationship_builders import CosineSimilarityBuilder, OverlapScoreBuilder
from ragas.testset.transforms.engine import Parallel
from ragas.utils import num_tokens_from_string

# Wrap LangChain LLM and Embeddings in RAGAS-compatible wrappers
generator_llm = LangchainLLMWrapper(llm)
generator_embeddings = LangchainEmbeddingsWrapper(embeddings)

# Initialise the generator
generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
)

# Balanced mix of simple, reasoning, and multi-context questions
query_distribution = default_query_distribution(generator_llm)

# ── Custom Transform Pipeline ─────────────────────────────────────────────────
# Only process DOCUMENT nodes that have enough content (>100 tokens)
def filter_doc(node):
    return node.type == NodeType.DOCUMENT and num_tokens_from_string(node.properties["page_content"]) > 100

# Process all DOCUMENT nodes (used for theme extraction)
def filter_docs(node):
    return node.type == NodeType.DOCUMENT

# Step 1: Summarise each document node using the LLM
summary_extractor = SummaryExtractor(llm=generator_llm, filter_nodes=filter_doc)

# Step 2: Convert summaries to embeddings for similarity comparison
summary_emb_extractor = EmbeddingExtractor(
    embedding_model=generator_embeddings,
    property_name="summary_embedding",
    embed_property_name="summary",
    filter_nodes=filter_doc,
)

# Step 3: Build cosine-similarity edges between document nodes
cosine_sim_builder = CosineSimilarityBuilder(
    property_name="summary_embedding",
    new_property_name="summary_similarity",
    threshold=0.5,
    filter_nodes=filter_doc,
)

# Extract named entities from each node (used for overlap scoring)
ner_extractor = NERExtractor(llm=generator_llm)

# Build edges based on shared named entities between nodes
ner_overlap_sim = OverlapScoreBuilder(threshold=0.01)

# Extract high-level themes from each document node
theme_extractor = ThemesExtractor(llm=generator_llm, filter_nodes=filter_docs)

# Filter out low-quality nodes that are unlikely to generate good questions
node_filter = CustomNodeFilter(llm=generator_llm)

# Run transforms: sequential steps where needed, parallel where independent
custom_transforms = [
    summary_extractor,                                               # Must run first (summaries needed for embeddings)
    node_filter,                                                     # Filter nodes before heavy processing
    Parallel(summary_emb_extractor, theme_extractor, ner_extractor), # Independent — run in parallel
    Parallel(cosine_sim_builder, ner_overlap_sim),                   # Build relationships in parallel
]

# Run in a separate thread to avoid asyncio/nest_asyncio/sniffio conflicts in Jupyter
_adv_result = {}

def _run_advanced_generation():
    try:
        _adv_result["testset"] = generator.generate_with_langchain_docs(
            documents=docs,
            testset_size=8,
            query_distribution=query_distribution,
            transforms=custom_transforms,
            raise_exceptions=False,
        )
    except Exception as e:
        _adv_result["error"] = e

thread = threading.Thread(target=_run_advanced_generation)
thread.start()
thread.join()

if "error" in _adv_result:
    raise _adv_result["error"]

testset = _adv_result["testset"]

C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\1429513678.py:21: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(llm)
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\1429513678.py:22: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(embeddings)
Applying SummaryExtractor: 100%|██████████| 3/3 [00:10<00:00,  3.34s/it]
Applying CustomNodeFilter: 100%|██████████| 3/3 [00:06<00:00,  2.09s/it]
Applying EmbeddingExtractor: 100%|██████████| 3/3 [00:08<00:00,  2.72s/it]
Applying ThemesExtractor:   0%|          | 0/3 [00:00<?, ?it/s]c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\euriai\langchain.py:323: RuntimeWarning: coroutine 'AsyncCallbackManagerForLLMRun.on_llm_error' was never awaited
  run_manager.on_llm_error(e)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Applying ThemesExtractor: 100%|██████████| 3/3 [00:07<00:00,  2.65s/it]
Applying NERExtractor: 100%|██████████| 3/3 [00:08<00:00,  2.71s/it]
Applying CosineSimilarityBuilder: 100%|██████████| 1/1 [00:00<00:00, 383.53it/s]
Applying OverlapScoreBuilder: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]
Generating personas: 100%|██████████| 3/3 [00:06<00:00,  2.27s/it]
Generating Scenarios: 100%|██████████| 3/3 [00:17<00:00,  5.82s/it]
Generating Samples: 100%|██████████| 9/9 [00:16<00:00,  1.83s/it]

In [60]:
testset.to_pandas()

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,What are the ingridients and price of caprese ...,"[margherita pizza; $12; classic with tomato, m...","Caprese salad consists of fresh tomatoes, mozz...",Chef Amico,MISSPELLED,LONG,single_hop_specific_query_synthesizer
1,What role does Nero d’Avola play in Chef Amico...,"[In the heart of the old quarter of Palermo, a...","At Chef Amico, Nero d’Avola is featured promin...",Chef Amico,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
2,What makes Cannoli a standout dessert in Sicil...,"[In the charming streets of Palermo, tucked aw...",Cannoli is considered the crown jewel of Sicil...,Italian Cuisine Enthusiast,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer
3,How did Amico's culinary journey and his exper...,[<1-hop>\n\nIn the heart of the old quarter of...,Amico's culinary journey was deeply influenced...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
4,What elements of Sicilian cuisine are reflecte...,[<1-hop>\n\nIn the heart of the old quarter of...,Chef Amico's restaurant embodies the essence o...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
5,How did Chef Amico's journey through Sicilian ...,[<1-hop>\n\nIn the heart of the old quarter of...,Chef Amico's journey through Sicilian cuisine ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
6,How did Chef Amico's upbringing in a Sicilian ...,[<1-hop>\n\nIn the charming streets of Palermo...,Chef Amico's upbringing in a Sicilian family s...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
7,What experiences in Italy shaped Chef Amico's ...,[<1-hop>\n\nIn the charming streets of Palermo...,Chef Amico's culinary journey was profoundly s...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer
8,What experiences in Amico's childhood influenc...,[<1-hop>\n\nIn the charming streets of Palermo...,Amico's childhood experiences in his Nonna Luc...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer

In [62]:
testset.to_pandas().shape

(9, 7)

In [63]:
# Build a Chroma vector store from the document chunks using Euriai embeddings.
# This is used by the retriever to find the most relevant context for each query.
vectorstore = Chroma.from_documents(chunks, embeddings)

# as_retriever() returns the top-k most similar chunks by default (k=4)
retriever = vectorstore.as_retriever()

print("Vector store built with", vectorstore._collection.count(), "chunks")

Vector store built with 33 chunks

In [64]:
# RAG prompt: instruct the LLM to answer ONLY from the retrieved context.
# This prevents hallucination by grounding the answer in the provided documents.
template = """Answer the question based only on the following context:
{context}

Question: {question}
"""

prompt = PromptTemplate(template=template, input_variables=["context", "question"])

In [65]:
# Build the RAG chain using LangChain Expression Language (LCEL):
#   1. Retriever fetches relevant document chunks for the question
#   2. RunnablePassthrough passes the original question through unchanged
#   3. Prompt formats context + question into a prompt string
#   4. llm generates an answer based on the prompt
#   5. StrOutputParser extracts the plain string from the LLM response
rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

In [66]:
# Load manually curated Q&A pairs from CSV.
# These serve as the ground truth for evaluation:
#   'question'     — the user query
#   'ground_truth' — the ideal reference answer
df = pd.read_csv("./questions_answers/qa.csv", delimiter=";")
questions = df["question"].tolist()
ground_truth = df["ground_truth"].tolist()

print(f"Loaded {len(questions)} evaluation questions")

Loaded 30 evaluation questions

In [67]:
df.head()

,question,ground_truth
0,Where was Amico born?,Amico was born in the heart of the old quarter...
1,What was Amico's early culinary influence?,Amico was influenced by the cooking in his Non...
2,What skill did Amico learn from Palermo's mark...,Amico learned to select the freshest fish and ...
3,Where in Italy did Amico gain culinary experie...,Amico gained culinary experience across variou...
4,"What is ""Chef Amico"" restaurant known for?",Chef Amico is known for combining Sicilian and...

In [113]:
from ragas.dataset_schema import SingleTurnSample, EvaluationDataset

# For each question:
#   1. Run the RAG chain to get the LLM-generated answer
#   2. Retrieve the context documents used to generate that answer
#   3. Package everything into a SingleTurnSample for RAGAS evaluation
#
# RAGAS 0.4 field names:
#   user_input        — the question asked
#   response          — the LLM-generated answer
#   retrieved_contexts — list of context strings used (from retriever)
#   reference         — the ground truth answer (from CSV)

samples = []
for query, gt in zip(questions, ground_truth):
    answer = rag_chain.invoke(query)
    contexts = [doc.page_content for doc in retriever.invoke(query)]
    samples.append(
        SingleTurnSample(
            user_input=query,
            response=answer,
            retrieved_contexts=contexts,
            reference=gt,
        )
    )

# Wrap all samples into an EvaluationDataset for batch evaluation
dataset = EvaluationDataset(samples=samples)
print(f"Built evaluation dataset with {len(samples)} samples")

Built evaluation dataset with 30 samples

In [ ]:
# ── RAGAS 0.4 renamed the fields from the old 0.1.x API ──────────────────────
# Old name (0.1.x)  →  New name (0.4.x)
#   question        →  user_input
#   contexts        →  retrieved_contexts
#   answer          →  response
#   ground_truth    →  reference
#
# We rename them back here just for readability — the actual RAGAS internals
# always use the new names (user_input, retrieved_contexts, response, reference).

dataset.to_pandas().rename(columns={
    "user_input":          "question",
    "retrieved_contexts":  "contexts",
    "response":            "answer",
    "reference":           "ground_truth",
}).head()

,user_input,retrieved_contexts,response,reference
0,Where was Amico born?,[Amico's life was deeply entwined with the vib...,Amico was born in the heart of the old quarter...,Amico was born in the heart of the old quarter...
1,What was Amico's early culinary influence?,[Amico's life was deeply entwined with the vib...,Amico's early culinary influence was his Nonna...,Amico was influenced by the cooking in his Non...
2,What skill did Amico learn from Palermo's mark...,"[From a young age, Amico was immersed in the a...",Amico learned to choose the freshest fish from...,Amico learned to select the freshest fish and ...
3,Where in Italy did Amico gain culinary experie...,"[As he grew, so did his desire to explore beyo...",Amico gained culinary experience in various re...,Amico gained culinary experience across variou...
4,"What is ""Chef Amico"" restaurant known for?",[Chef Amico’s doors opened to a world where th...,Chef Amico restaurant is known for its warm an...,Chef Amico is known for combining Sicilian and...

In [115]:
from ragas import evaluate
# ── Correct import path for RAGAS 0.4 is ragas.metrics (NOT ragas.metrics.collections) ──
from ragas.metrics import (
    Faithfulness,                      # Is the answer grounded in the retrieved context? (no hallucinations)
    AnswerRelevancy,                   # Is the answer relevant and complete for the question?
    LLMContextRecall,                  # Did the retriever fetch all info needed to answer?
    LLMContextPrecisionWithReference,  # Are relevant chunks ranked higher than irrelevant ones?
    ContextRelevance,                  # Is the retrieved context relevant to the question?
)

# Wrap LLM and Embeddings in RAGAS-compatible wrappers for the evaluator
# - LLM is used to judge: Faithfulness, ContextRecall, ContextPrecision, ContextRelevance
# - Embeddings are used for: AnswerRelevancy (cosine similarity between questions)
eval_llm = LangchainLLMWrapper(llm)
eval_embeddings = LangchainEmbeddingsWrapper(embeddings)

metrics = [
    ContextRelevance(),
    LLMContextPrecisionWithReference(),
    LLMContextRecall(),
    Faithfulness(),
    AnswerRelevancy(),
]

print("Metrics configured:", [type(m).__name__ for m in metrics])

Metrics configured: ['ContextRelevance', 'LLMContextPrecisionWithReference', 'LLMContextRecall', 'Faithfulness', 'AnswerRelevancy']

C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:3: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:3: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:3: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:3: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:3: DeprecationWarning: Importing ContextRelevance from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextRelevance
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:14: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(llm)
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\294396069.py:15: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(embeddings)

In [ ]:
import asyncio
import threading
from ragas import aevaluate

_eval_result = {}

# ── Define the async evaluation coroutine ────────────────────────────────────
# All LLM/embedding/metric objects are created INSIDE this async function so
# that any async HTTP clients are bound to the SAME event loop that runs them.
async def _eval_async(eval_dataset):
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from ragas.metrics import (
        Faithfulness,
        AnswerRelevancy,
        LLMContextRecall,
        LLMContextPrecisionWithReference,
        ContextRelevance,
    )
    _llm  = LangchainLLMWrapper(llm)
    _emb  = LangchainEmbeddingsWrapper(embeddings)
    _metrics = [
        ContextRelevance(),
        LLMContextPrecisionWithReference(),
        LLMContextRecall(),
        Faithfulness(),
        AnswerRelevancy(),
    ]
    return await aevaluate(
        dataset=eval_dataset,
        metrics=_metrics,
        llm=_llm,
        embeddings=_emb,
        raise_exceptions=False,
    )

# ── Run in a fresh thread with its own event loop ────────────────────────────
# Python 3.12+ asyncio.wait_for() requires being inside a proper asyncio Task.
# A fresh thread + loop.run_until_complete() creates that Task context cleanly,
# with no interference from Jupyter's existing event loop.
def _run_in_thread(eval_dataset):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        _eval_result["result"] = loop.run_until_complete(_eval_async(eval_dataset))
    except Exception as e:
        _eval_result["error"] = e
    finally:
        loop.close()

eval_thread = threading.Thread(target=_run_in_thread, args=(dataset,))
eval_thread.start()
eval_thread.join()

if "error" in _eval_result:
    raise _eval_result["error"]

result = _eval_result["result"]
print(result)

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

RuntimeError: Timeout should be used inside a task

In [111]:
result.to_pandas()

,user_input,retrieved_contexts,response,reference,nv_context_relevance,llm_context_precision_with_reference,context_recall,faithfulness,answer_relevancy
0,Where was Amico born?,[Amico's life was deeply entwined with the vib...,Amico was born in the heart of the old quarter...,Amico was born in the heart of the old quarter...,NaN,NaN,NaN,NaN,NaN
1,What was Amico's early culinary influence?,[Amico's life was deeply entwined with the vib...,Amico's early culinary influence was his Nonna...,Amico was influenced by the cooking in his Non...,NaN,NaN,NaN,NaN,NaN
2,What skill did Amico learn from Palermo's mark...,"[From a young age, Amico was immersed in the a...",Amico learned to choose the freshest fish from...,Amico learned to select the freshest fish and ...,NaN,NaN,NaN,NaN,NaN
3,Where in Italy did Amico gain culinary experie...,"[As he grew, so did his desire to explore beyo...",Amico gained culinary experience throughout It...,Amico gained culinary experience across variou...,NaN,NaN,NaN,NaN,NaN
4,"What is ""Chef Amico"" restaurant known for?",[Chef Amico’s doors opened to a world where th...,Chef Amico restaurant is known for its warm an...,Chef Amico is known for combining Sicilian and...,NaN,NaN,NaN,NaN,NaN
5,What does Amico's restaurant menu reflect?,"[At Chef Amico, every dish told a story. The m...",Amico's restaurant menu reflects a tapestry of...,The menu reflects Amico's culinary journey and...,NaN,NaN,NaN,NaN,NaN
6,How does Amico perceive hospitality?,"[For Amico, hospitality was an art form. He be...",Amico perceives hospitality as an art form and...,Amico sees hospitality as an art of celebratin...,NaN,NaN,NaN,NaN,NaN
7,"What distinguishes ""Chef Amico"" in Palermo?","[Returning to Palermo with a vision, Amico ope...","""Chef Amico"" is distinguished in Palermo by it...",Chef Amico is distinguished by Amico's dedicat...,NaN,NaN,NaN,NaN,NaN
8,What activities does Amico engage in besides c...,[Amico's life was deeply entwined with the vib...,"Besides cooking, Amico engages in mentoring yo...","Amico mentors young chefs, conducts culinary w...",NaN,NaN,NaN,NaN,NaN
9,How is Amico's legacy beyond his dishes?,[Amico’s legacy is not just in the dishes he c...,Amico's legacy extends beyond his dishes throu...,Amico's legacy lies in his community involveme...,NaN,NaN,NaN,NaN,NaN
10,"What is ""Chef Amico"" restaurant's setting?","[Creating Chef Amico’s Restaurant, Chef Amico’...",Chef Amico's restaurant is set in the charming...,Chef Amico is set in a quaint alley in Palermo.,NaN,NaN,NaN,NaN,NaN
11,"What atmosphere does ""Chef Amico"" have?",[Chef Amico’s doors opened to a world where th...,"Chef Amico has a warm and inviting atmosphere,...",Chef Amico has a welcoming atmosphere with aro...,NaN,NaN,NaN,NaN,NaN
12,What do the restaurant's walls signify?,[Chef Amico’s doors opened to a world where th...,The restaurant's walls signify a rich culinary...,The walls showcase Amico's travels and family ...,NaN,NaN,NaN,NaN,NaN
13,What dishes did food critic Elena Rossi try at...,"[One evening, as the sun cast a golden glow ov...","Elena Rossi tried Cannoli, which is described ...","Elena Rossi tried Caponata, Risotto al Nero di...",NaN,NaN,NaN,NaN,NaN
14,"What is the significance of ""Caponata"" in the ...",[Elena was led to a table adorned with a simpl...,"In the menu, ""Caponata"" is significant as it i...","Caponata is a blend of eggplant, capers, and s...",NaN,NaN,NaN,NaN,NaN
15,"What story does ""Risotto al Nero di Seppia"" tell?",[Elena was led to a table adorned with a simpl...,"The ""Risotto al Nero di Seppia"" tells the tale...",This dish tells the story of Sicily's relation...,NaN,NaN,NaN,NaN,NaN
16,"What does the ""Cannoli"" dessert represent?","[The final masterpiece was Cannoli, the crown ...","The ""Cannoli"" dessert represents the stories, ...",Cannoli represents the quintessence of Sicilia...,NaN,NaN,NaN,NaN,NaN
17,"What was Elena Rossi's impression of ""Chef Ami...","[One evening, as the sun cast a golden glow ov...","Elena Rossi's impression of ""Chef Amico"" was v...",Elena Rossi was impressed by the restaurant's ...,NaN,NaN,NaN,NaN,NaN
18,"What makes ""Chef Amico"" unique as a dining spot?",[Chef Amico’s doors opened to a world where th...,"""Chef Amico"" is unique as a dining spot due to...",Chef Amico is unique for its fusion of culinar...,NaN,NaN,NaN,NaN,NaN
19,"What does each meal at ""Chef Amico"" symbolize?","[At Chef Amico, every dish told a story. The m...","Each meal at ""Chef Amico"" symbolizes a story, ...","Each meal at ""Chef Amico"" symbolizes a journey...",NaN,NaN,NaN,NaN,NaN
20,What is the origin of Amico's passion for cook...,[Amico's life was deeply entwined with the vib...,Amico's passion for cooking originated in the ...,Amico's passion originated from his experience...,NaN,NaN,NaN,NaN,NaN
21,How did Amico's upbringing influence his cooki...,[Amico's life was deeply entwined with the vib...,Amico's upbringing significantly influenced hi...,His upbringing in Palermo influenced his cooki...,NaN,NaN,NaN,NaN,NaN
22,What culinary traditions influenced Amico?,[Amico's life was deeply entwined with the vib...,Amico was influenced by the vibrant essence of...,Amico was influenced by the diverse culinary t...,NaN,NaN,NaN,NaN,NaN
23,"How does ""Chef Amico"" reflect Amico's experien...","[The Journey to Chef Amico, At Chef Amico, eve...","""Chef Amico"" reflects Amico's experiences by s...",The restaurant reflects Amico's travels and th...,NaN,NaN,NaN,NaN,NaN
24,"What is the culinary philosophy at ""Chef Amico""?","[At Chef Amico, every dish told a story. The m...","The culinary philosophy at ""Chef Amico"" center...",The philosophy is about crafting meals that ce...,NaN,NaN,NaN,NaN,NaN
25,How does Amico's restaurant contribute to the ...,[Amico’s legacy is not just in the dishes he c...,Amico's restaurant contributes to the communit...,It contributes by being a gathering place and ...,NaN,NaN,NaN,NaN,NaN
26,How has Amico's journey shaped his restaurant'...,"[At Chef Amico, every dish told a story. The m...",Amico's journey has shaped his restaurant's me...,His journey has infused the menu with a blend ...,NaN,NaN,NaN,NaN,NaN
27,"Why is ""Chef Amico"" considered more than a res...",[Amico’s legacy is not just in the dishes he c...,"""Chef Amico"" is considered more than a restaur...",It is considered a cultural hub that embodies ...,NaN,NaN,NaN,NaN,NaN
28,How did Amico's travels enhance his culinary s...,"[As he grew, so did his desire to explore beyo...",Amico's travels enhanced his culinary skills b...,His travels across Italy introduced him to var...,NaN,NaN,NaN,NaN,NaN
29,"What does the future hold for ""Chef Amico"" and...","[The Journey to Chef Amico, Amico’s legacy is ...","The future for ""Chef Amico"" and Amico appears ...",The future involves continuing to serve as a c...,NaN,NaN,NaN,NaN,NaN

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

# Convert RAGAS results to a DataFrame
df_results = result.to_pandas()

print("Available columns:", df_results.columns.tolist())

# ── Dynamically detect metric columns ────────────────────────────────────────
# RAGAS 0.4 metric names can differ from the class name (e.g. ContextRelevance
# has internal name 'nv_context_relevance', LLMContextRecall → 'context_recall').
# We detect them automatically by excluding the known input/output columns.
non_metric_cols = {"user_input", "response", "retrieved_contexts", "reference"}
metric_cols = [
    c for c in df_results.columns
    if c not in non_metric_cols and pd.api.types.is_numeric_dtype(df_results[c])
]

print("Metric columns found:", metric_cols)

if not metric_cols:
    print("No metric columns found — all scores may still be NaN. Check LLM errors above.")
else:
    heatmap_data = df_results[metric_cols]

    # Red → Green colormap: red = poor score (0.0), green = good score (1.0)
    cmap = LinearSegmentedColormap.from_list("red_green", ["red", "yellow", "green"])

    fig, ax = plt.subplots(figsize=(max(8, len(metric_cols) * 2), max(6, len(df_results) * 0.5)))
    sns.heatmap(
        heatmap_data,
        annot=True,
        fmt=".2f",
        linewidths=0.5,
        cmap=cmap,
        vmin=0,
        vmax=1,
        ax=ax,
    )

    # Use shortened question labels on Y-axis (RAGAS 0.4 field: 'user_input')
    labels = [q[:60] + "…" if len(q) > 60 else q for q in df_results["user_input"]]
    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels, rotation=0, fontsize=8)
    ax.set_title("RAGAS Evaluation Results")
    plt.tight_layout()
    plt.show()

In [127]:
import asyncio
import threading
from ragas.dataset_schema import SingleTurnSample, EvaluationDataset
from ragas import aevaluate

# ── Single-sample spot-check ──────────────────────────────────────────────────
# Build one sample using the RAGAS 0.4 field names.
# Mapping from old (0.1.x) → new (0.4.x):
#   question     → user_input
#   contexts     → retrieved_contexts
#   answer       → response
#   ground_truth → reference

single_sample = SingleTurnSample(
    user_input="What is the capital of France?",           # question
    retrieved_contexts=["Paris is the capital and most populous city of France."],  # contexts
    response="The capital of France is Paris.",            # answer
    reference="Paris",                                     # ground_truth
)

single_dataset = EvaluationDataset(samples=[single_sample])

# Preview with familiar column names
single_dataset.to_pandas().rename(columns={
    "user_input":         "question",
    "retrieved_contexts": "contexts",
    "response":           "answer",
    "reference":          "ground_truth",
})

,question,contexts,answer,ground_truth
0,What is the capital of France?,[Paris is the capital and most populous city o...,The capital of France is Paris.,Paris

In [128]:
import asyncio
import threading
from ragas import aevaluate

# ── Evaluate the single sample ────────────────────────────────────────────────
_single_eval = {}

async def _eval_single_async():
    from ragas.llms import LangchainLLMWrapper
    from ragas.embeddings import LangchainEmbeddingsWrapper
    from ragas.metrics import (
        Faithfulness,
        AnswerRelevancy,
        LLMContextRecall,
        LLMContextPrecisionWithReference,
        ContextRelevance,
    )
    return await aevaluate(
        dataset=single_dataset,
        metrics=[
            ContextRelevance(),
            LLMContextPrecisionWithReference(),
            LLMContextRecall(),
            Faithfulness(),
            AnswerRelevancy(),
        ],
        llm=LangchainLLMWrapper(llm),
        embeddings=LangchainEmbeddingsWrapper(embeddings),
        raise_exceptions=False,
    )

def _run_single():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        _single_eval["result"] = loop.run_until_complete(_eval_single_async())
    except Exception as e:
        _single_eval["error"] = e
    finally:
        loop.close()

t = threading.Thread(target=_run_single)
t.start()
t.join()

if "error" in _single_eval:
    raise _single_eval["error"]

single_result = _single_eval["result"]

# Show results with familiar column names
single_result.to_pandas().rename(columns={
    "user_input":         "question",
    "retrieved_contexts": "contexts",
    "response":           "answer",
    "reference":          "ground_truth",
})

C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:11: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:11: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:11: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:11: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:11: DeprecationWarning: Importing ContextRelevance from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextRelevance
  from ragas.metrics import (
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:27: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  llm=LangchainLLMWrapper(llm),
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:28: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  embeddings=LangchainEmbeddingsWrapper(embeddings),
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\2864525457.py:18: DeprecationWarning: aevaluate() is deprecated and will be removed in a future version. Use the @experiment decorator instead. See https://docs.ragas.io/en/latest/concepts/experiment/ for more information.
  return await aevaluate(
Evaluating:   0%|          | 0/5 [00:00<?, ?it/s]Exception raised in Job[0]: RuntimeError(Timeout should be used inside a task)
c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\ragas\executor.py:84: RuntimeWarning: coroutine 'ContextRelevance._single_turn_ascore' was never awaited
  return counter, np.nan
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception raised in Job[1]: RuntimeError(Timeout should be used inside a task)
c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\ragas\executor.py:84: RuntimeWarning: coroutine 'LLMContextPrecisionWithReference._single_turn_ascore' was never awaited
  return counter, np.nan
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception raised in Job[2]: RuntimeError(Timeout should be used inside a task)
c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\ragas\executor.py:84: RuntimeWarning: coroutine 'LLMContextRecall._single_turn_ascore' was never awaited
  return counter, np.nan
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception raised in Job[3]: RuntimeError(Timeout should be used inside a task)
c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\ragas\executor.py:84: RuntimeWarning: coroutine 'Faithfulness._single_turn_ascore' was never awaited
  return counter, np.nan
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception raised in Job[4]: RuntimeError(Timeout should be used inside a task)
c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\ragas\executor.py:84: RuntimeWarning: coroutine 'ResponseRelevancy._single_turn_ascore' was never awaited
  return counter, np.nan
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Evaluating: 100%|██████████| 5/5 [00:00<00:00, 669.01it/s]

,question,contexts,answer,ground_truth,nv_context_relevance,llm_context_precision_with_reference,context_recall,faithfulness,answer_relevancy
0,What is the capital of France?,[Paris is the capital and most populous city o...,The capital of France is Paris.,Paris,NaN,NaN,NaN,NaN,NaN

In [151]:
# =============================
# Imports
# =============================
from euriai.langchain import create_chat_model
from euriai.langchain import EuriaiEmbeddings

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

# ⚠️ CRITICAL: import from langchain_core, not langchain.chains
from langchain_core.output_parsers import StrOutputParser

from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
from datasets import Dataset

C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\1126967778.py:19: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\1126967778.py:19: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\1126967778.py:19: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\1126967778.py:19: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall

In [159]:
# =====================================================
# 1. Documents
# =====================================================
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

documents = [
    Document(page_content="Retrieval Augmented Generation combines retrieval with LLMs."),
    Document(page_content="RAG improves factual accuracy using external documents."),
    Document(page_content="LangChain is a framework for building LLM applications."),
]

# =====================================================
# 2. Split Docs
# =====================================================
splitter = RecursiveCharacterTextSplitter(chunk_size=250, chunk_overlap=40)
docs = splitter.split_documents(documents)

# =====================================================
# 3. Vector Store
# =====================================================
embeddings = EuriaiEmbeddings(
    api_key=api_key,
    model="text-embedding-3-small"
)

vectorstore = FAISS.from_documents(docs, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

# =====================================================
# 4. LLM
# =====================================================

#llm = create_chat_model(api_key=api_key, model="gpt-4o-mini", temperature=0.1)
llm = ChatOpenAI(
    model="stepfun/step-3.5-flash:free",
    base_url="https://openrouter.ai/api/v1",
    api_key="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",
)

# =====================================================
# 5. Prompt
# =====================================================
prompt = ChatPromptTemplate.from_template(
    """Answer the question using the following context only.

Context:
{context}

Question:
{question}
"""
)

# =====================================================
# 6. Chain (FIXED)
# =====================================================
rag_chain = (
    {
        "docs": retriever,
        "question": RunnablePassthrough(),
    }
    | RunnableLambda(lambda x: {
        "context": format_docs(x["docs"]),
        "question": x["question"],
        "docs": x["docs"],   # keep raw docs
    })
    | RunnableLambda(lambda x: {
        "answer": llm.invoke(prompt.format(**x)).content,
        "contexts": [doc.page_content for doc in x["docs"]],
    })
)

# =====================================================
# 7. Run RAG
# =====================================================
question = "What is Retrieval Augmented Generation?"
response = rag_chain.invoke(question)

answer = response["answer"]
contexts = response["contexts"]

# =====================================================
# 8. RAGAS Dataset
# =====================================================
dataset = Dataset.from_dict({
    "question": [question],
    "answer": [answer],
    "contexts": [contexts],  # list of list
    "ground_truth": [
        "Retrieval Augmented Generation improves LLM responses by retrieving relevant documents."
    ],
})

# =====================================================
# 9. RAGAS Evaluation
# =====================================================

from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

ragas_llm = LangchainLLMWrapper(llm)
ragas_embeddings = LangchainEmbeddingsWrapper(embeddings)

scores = evaluate(
    dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_precision,
        context_recall,
    ],llm=ragas_llm, embeddings=ragas_embeddings, raise_exceptions=True
)

print("Answer:\n", answer)

print("\nContexts:")
for c in contexts:
    print("-", c)

print("\nRAGAS Scores:\n", scores)

C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\691531207.py:102: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  ragas_llm = LangchainLLMWrapper(llm)
C:\Users\C90008809\AppData\Local\Temp\ipykernel_9972\691531207.py:103: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_embeddings = LangchainEmbeddingsWrapper(embeddings)
Evaluating:   0%|          | 0/4 [00:00<?, ?it/s]

RuntimeError: Timeout should be used inside a task

In [157]:
[contexts]

[['Retrieval Augmented Generation combines retrieval with LLMs.',
  'RAG improves factual accuracy using external documents.']]

In [1]:
print(1)

1

In [1]:
# =============================
# Imports
# =============================
from euriai.langchain import create_chat_model
from euriai.langchain import EuriaiEmbeddings

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

# ⚠️ CRITICAL: import from langchain_core, not langchain.chains
from langchain_core.output_parsers import StrOutputParser

from ragas import evaluate, aevaluate
from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
from datasets import Dataset

import nest_asyncio
import asyncio

# =====================================================
# 1. Documents
# =====================================================
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

documents = [
    Document(page_content="Retrieval Augmented Generation combines retrieval with LLMs."),
    Document(page_content="RAG improves factual accuracy using external documents."),
    Document(page_content="LangChain is a framework for building LLM applications."),
]

# =====================================================
# 2. Split Docs
# =====================================================
splitter = RecursiveCharacterTextSplitter(chunk_size=250, chunk_overlap=40)
docs = splitter.split_documents(documents)

# =====================================================
# 3. Vector Store
# =====================================================
embeddings = EuriaiEmbeddings(
    api_key="euri-49e67794160469861d51db4b89da0c40be0457fd1303002d1fbf682ad44c512e",
    model="text-embedding-3-small"
)

vectorstore = FAISS.from_documents(docs, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

# =====================================================
# 4. LLM
# =====================================================

#llm = create_chat_model(api_key=api_key, model="gpt-4o-mini", temperature=0.1)
llm = ChatOpenAI(
    model="stepfun/step-3.5-flash:free",
    base_url="https://openrouter.ai/api/v1",
    api_key="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",
)

print(llm.invoke("What is the capital of France?").content)

# =====================================================
# 5. Prompt
# =====================================================
prompt = ChatPromptTemplate.from_template(
    """Answer the question using the following context only.

Context:
{context}

Question:
{question}
"""
)

# =====================================================
# 6. Chain (FIXED)
# =====================================================
rag_chain = (
    {
        "docs": retriever,
        "question": RunnablePassthrough(),
    }
    | RunnableLambda(lambda x: {
        "context": format_docs(x["docs"]),
        "question": x["question"],
        "docs": x["docs"],   # keep raw docs
    })
    | RunnableLambda(lambda x: {
        "answer": llm.invoke(prompt.format(**x)).content,
        "contexts": [doc.page_content for doc in x["docs"]],
    })
)

# =====================================================
# 7. Run RAG
# =====================================================
question = "What is Retrieval Augmented Generation?"
response = rag_chain.invoke(question)

answer = response["answer"]
contexts = response["contexts"]

print(contexts)
print(answer)

# =====================================================
# 8. RAGAS Dataset
# =====================================================
dataset = Dataset.from_dict({
    "question": [question],
    "answer": [answer],
    "contexts": [contexts],  # list of list
    "ground_truth": [
        "Retrieval Augmented Generation improves LLM responses by retrieving relevant documents."
    ],
})

# =====================================================
# 9. RAGAS Evaluation
# =====================================================

from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
import asyncio

ragas_llm = LangchainLLMWrapper(llm)
ragas_embeddings = LangchainEmbeddingsWrapper(embeddings)

# Apply nest_asyncio to allow nested loops in Jupyter
nest_asyncio.apply()

scores = await aevaluate(
    dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_precision,
        context_recall,
    ],llm=ragas_llm, embeddings=ragas_embeddings, raise_exceptions=True)

print("Answer:\n", answer)

print("\nContexts:")
for c in contexts:
    print("-", c)

print("\nRAGAS Scores:\n", scores)

c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\langchain_core\_api\deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
c:\EGA\code\RAG\Udemy_RAG_1\Udemy-Advanced-LangChain\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:19: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:19: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:19: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:19: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall

The capital of France is **Paris**.

C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:132: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  ragas_llm = LangchainLLMWrapper(llm)
C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:133: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_embeddings = LangchainEmbeddingsWrapper(embeddings)
C:\Users\C90008809\AppData\Local\Temp\ipykernel_28368\2522151943.py:138: DeprecationWarning: aevaluate() is deprecated and will be removed in a future version. Use the @experiment decorator instead. See https://docs.ragas.io/en/latest/concepts/experiment/ for more information.
  scores = await aevaluate(

['Retrieval Augmented Generation combines retrieval with LLMs.', 'RAG improves factual accuracy using external documents.']
Retrieval Augmented Generation (RAG) is a method that combines retrieval with large language models (LLMs) to improve factual accuracy by utilizing external documents.

Evaluating:   0%|          | 0/4 [00:00<?, ?it/s]

RuntimeError: Timeout should be used inside a task